# Site
repository: olgakozhar/olgakozhar.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Olga Kozhar PhD
title: Research Scientist
email: okozhar@gmail.com 
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: olgakozhar
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-0976-7334

# Additional icon links
additional_links:
- title: scholar.google.com
  icon: fas fa-globe
  url: https://scholar.google.com/citations?user=FHZ9QSIAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/olga_cropped.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a biologist interested in ecology, population genomics, and evolution of microbes and their host plants. I hold a PhD degree in Plant Pathology from Washington State University. Currently I am focused on understanding processes leading to the emergence of fungal diseases of plants under climate change. For this I use field observations, molecular data, evolutionary theory, and modern computational tools. Being broadly interested in science, I get excited about research initiatives focused on identifying genetic signatures of organismal adaptation and how these mechanisms can be used to enhance sustainable food production and improve ecosystems health. I also teach a graduate course on Biology and Genetics of Fungal Plant Pathogens at Colorado State University, mentor undergraduate and graduate students, and spend a lot of free time in nature with my dog.

  I am most skilled in: <mark>Molecular Biology</mark> <mark>Genomics</mark> and <mark>Plant Disease Ecology</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Exploring microbiome for disease management
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Connecting climate, microbiome, and phenotypic data to understand disease evolution
        description: | # this will include new lines to allow paragraphs
          I started this project in spring of 2023 as a collaboration between Stewartlab and USDA Forest Service. I am using climate, phenotypic, metagenomic, and metatranscriptomic data from pine needles to understand what drives recent loblolly pine tree decline across southeastern region of USA. With this I want to learn what members of needle microbiome are associated with the disease, how microbial communities change during season, and what climatic factors are associated with disease severity. This information will be used for the development of a disease risk assessment management tool.
      - layout: top-middle
        title: Long-term effects of invasions on ecosystems
        link: https://doi.org/10.1016/j.funbio.2023.11.005
        # link_text: Project Website
        quote: >
          Investigating new opportunities for pathogen evolution in globalization era
        description: | # this will include new lines to allow paragraphs
          With the world being interconnected, we also connect ecosystems. This in turn puts organisms, previously isolated, into contact. This is one of many ways how human activities drive evolution of other organisms. Combining phenotypic and genetic data, I investigated distribution, genetics, and pathogenicity of a recently identified hybrid of native and invasive fungal pathogens of forest ecosystems in western USA. In future, I plan to sequence genomes of these hybrids to better understand mechanisms of their evolution.
      - layout: top-middle
        title: Bacterial population genomics
        link: https://doi.org/10.1038/s41598-023-41976-8
        quote: >
          Studying populations of emerging pathogen of oak trees in western USA
        description: |
          Utilizing whole genome sequencing, I studied the phylogenetic relationship and diversity of two populations of the bacterial oak pathogen Lonsdalea quercina from western North America and compared these populations to other Lonsdalea species found worldwide. 
      - layout: top-middle
        title: Designing molecular tests for plant pathogens
        link: https://doi.org/10.1111/efp.12814
        quote: >
          Creating tools for pathogen identification
        description: |
          Together with my colleague Jorge Ibarra Caballero, I designed genetic - based assay for identification of invasive forest pathogen. This assay requires minimum training, accessable equipment, and can be used directly in field.
      - layout: top-middle
        title: Disease emergence in changing environments
        link: https://doi.org/10.1111/mec.16384
        quote: >
          Using genomic data and machine learning to understand pathogen evolution
        description: |
          Applying principles of population genetics, coalescent theory, and supervised machine learning to genomic data I studied ecological and evolutionary processes that promote emergence of tropical tree pathogen Phellinus noxius.
      - layout: top-middle
        title: Linking disease ecology, evolution, and sustainable disease management
        link: https://journals.asm.org/doi/10.1128/aem.02908-19
        #additional_links:
       # - title:  https://apsjournals.apsnet.org/doi/full/10.1094/PHYTO-01-18-0016-R
           # icon: fas fa-globe
        #    url: https://apsjournals.apsnet.org/doi/full/10.1094/PHYTO-01-18-0016-R
        #   - title:  https://bsppjournals.onlinelibrary.wiley.com/doi/abs/10.1111/ppa.13284
         #    icon: fas fa-globe
         #    url: https://bsppjournals.onlinelibrary.wiley.com/doi/abs/10.1111/ppa.13284
        quote: >
          Ecology and population biology of gray mold fungus on berries
        description: |
          This was my PhD project that I completed at WSU. During exciting and challening years of grad school I learned a ton about infection process of red raspberry by Botrytis cinerea in the Pacific Northwest, dived into microbial evolution and its adaptation to antrhopogenic environments, and ate a lot of berries. Results of my work helped farmers improve disease management and decrease amount of fungicides used in fields.

  - title: Research talks # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Conference talks
        quote: >
          I love talking about science and regularly present my research at conferences and public meetings
        description: | # this will include new lines to allow paragraphs
            - Pathogen emergence in changing ecosystems: case study with Phellinus noxius in Eastern Asia, Australia, and the Pacifi c Islands. International Congress of Plant Pathology 2023. Lyon, France.
            - Emerging tree pathogen Phellinus noxius has a long evolutionary history in Eastern Asia, Australia, and the Pacifi c Islands. Fungal Genetics Conference Fungal22. March 19th, 2022. Pacifi c Grove, CA, USA.
            - Detection and distribution of Cronartium ribicola and Cronartium comandrae hybrids in Colorado and Wyoming forests, USA. American Phytopathological Society Annual Meeting Plant Health 2021. August 2nd, 2021. Online.
            - Population structure and pathways of spread of an emerging tree root pathogen Phellinus noxius in Southeast Asia, Australia, and the Pacifi c Islands. American Phytopathological Society Pacifi c Division Meeting. June 16th, 2021. Online.
            - Insights into population structure of Botrytis cinerea infecting small fruit in the Pacifi c Northwest. American Phytopathological Society Annual Meeting Plant Health 2020. August 12th, 2020. Fort Collins, CO.
            - Populations of Botrytis cinerea infecting small fruit in the Pacifi c Northwest. American Phytopathological Society Pacifi c Division Meeting. June 26th, 2019. Fort Collins, CO.
            - Biology and fungicide resistance of Botrytis cinerea on small fruit in Washington. Annual Berry Disease meeting. February 21st, 2019. Lynden, WA.
            - Dynamics of Botrytis cinerea colonization of red raspberry flowers and fruit. Washington Small Fruit Conference & Ag Show. November 28th, 2018. Lynden, WA.
            - Effects of fungicide applications on Botrytis cinerea colonization of red raspberry at different developmental stages of the host. Annual Berry Disease meeting. February 21st, 2018. Lynden, WA.
            - Do early-season fungicide applications decrease Botrytis fruit rot of red raspberry? Washington Small Fruit Conference. December 15st, 2017. Lynden, WA.
            - How does Botrytis cinerea infect red raspberry? American Phytopathological Society Annual Meeting. July 30th, 2017. San Antonio, TX.
      - layout: top-middle
        title: Conference posters
        description: | # this will include new lines to allow paragraphs  
            - Temporal and spatial distribution of interspecifi c hybrid of two tree rust pathogens in subalpine ecosystems of western USA. Plant Health 2023. August 12th, 2023. Denver, CO.
            - Population genomic analysis of Lonsdalea quercina, an emerging pathogen affecting various species of oaks in Colorado and California. Plant Health 2022. August 10th, 2022. Pittsburgh, PA.
            - Botrytis cinerea population structure on small fruit in the Pacifi c Northwest. Washington State University Mount Vernon Research and Extension Center Field Day. July 7th, 2019. Mount Vernon, WA.
            - Insights into Botrytis cinerea population structure on small fruit in the Pacifi c Northwest. 30th Fungal genetics conference. March 15th, 2019. Pacifi c Grove, CA.
            - Colonization dynamics of red raspberry flowers and fruit by Botrytis cinerea. International Congress of Plant Pathology. July 31st, 2018. Boston, MA.
            - What do we know about population structure of Botrytis cinerea infecting small fruit in the Pacific Northwest? Annual Conference of Northwest Center for Small Fruits Research. December 8th, 2016. Kennewick, WA.
            - Phylogenetic analysis of a morphologically distinct morel (Morchella spp) from the US Inland Pacifi c Northwest. 84th Annual Meeting of Mycological Society of America. August 5th, 2016. Berkeley, CA.
            - Biology of Botrytis fruit rot on red raspberry. Washington Small Fruit Conference. December 4th, 2015. Lynden, WA.
      - layout: top-middle
        title: Outreach
        description: | # this will include new lines to allow paragraphs  
            - Pests and diseases of forest and residential trees. Earth Day K-12 presentation for Werner Elementary School. April 23d, 2021. Fort Collins, CO.
            - Dynamics of Botrytis cinerea colonization of red raspberry flowers and fruit. Washington Berry Research Review. November 1st, 2018. Mount Vernon, WA.
            - Control of gray mold of berries in the Pacifi c Northwest. Skagit Berry Workshop. March, 23d, 2018. Mount Vernon, WA.
            - Population biology of Botrytis cinerea on small fruit in the Pacifi c Northwest. Berry Fungicide Resistance Working Group. February 22nd, 2017. Lynden, WA.
            - Botrytis fruit rot on red raspberry: are flowers important for the development of gray mold? Washington State University Mount Vernon Research and Extension Center Field Day. July 7th, 2016. Mount Vernon, WA.
            - Biology and ecology of Botrytis fruit rot on red raspberry. Washington State University Mount Vernon Research and Extension Center Field Day. July 5th, 2015. Mount Vernon, WA.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in science some of my other interests and hobbies are:
      - Rock climbing
      - Cycling
      - Hiking
      - Gardening
      - Mixing music
      - Art and craft projects


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
