# Site
repository: olgakozhar/olgakozhar.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Olga Kozhar PhD
title: Research Scientist
email: okozhar@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: olgakozhar
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-0976-7334

# Additional icon links
additional_links:
- title: scholar.google.com
  icon: fas fa-globe
  url: https://scholar.google.com/citations?user=FHZ9QSIAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/olga_cropped.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a biologist interested in ecology, population genomics, and evolution of microbes and their host plants. I hold a PhD degree in Plant Pathology from Washington State University. I am currently focused on understanding processes leading to the emergence of fungal diseases of plants under climate change. For this I use field observations, molecular data, evolutionary theory, and modern computational tools. Being broadly interested in science, I get excited about research initiatives focused on unraveling genetic signatures of organismal adaptation and how these mechanisms can be used to enhance sustainable food production and improve ecosystems health. I also teach a graduate course on Biology and Genetics of Fungal Plant Pathogens at Colorado State University, mentor undergraduate and graduate students, and spend a lot of free time in nature with my dog.

  I am most skilled in: <mark>Molecular Biology</mark>, <mark>Genomics</mark> and <mark>Plant Disease Ecology</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Exploring microbiome for disease management
        #link: github.com/sproogen
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Connecting climate, microbiome, and phenotypic data to understand disease evolution
        description: | # this will include new lines to allow paragraphs
          I started this project in spring of 2023 as a collaboration between Stewartlab and USDA Forest Service. I am using climate, phenotypic, metagenomics, and metatranscriptomics data from pine needles to understand what drives recent loblolly pine tree decline across southeastern region of USA. With this I want to learn what members of needle microbiome are associated with the disease, how microbial communities change during season, and what climatic factors are associated with disease severity. In the end this information will be used for the development of a disease risk assessment management tool.
      - layout: top-middle
        title: Long-term effects of invasions on ecosystems
        link: https://doi.org/10.1016/j.funbio.2023.11.005
        # link_text: Project Website
        quote: >
          Investigating new opportunities for pathogen evolution in globalization era
        description: | # this will include new lines to allow paragraphs
          With the world being interconnected, we also connect ecosystems. This in turn puts organisms, previously isolated, into contact. This is one of many ways how human activities drive evolution of other organisms. Combining phenotypic and genetic data, I investigated distribution, genetics, and pathogenicity of a recently identified hybrid of native and invasive fungal pathogens of forest ecosystems in western USA. In future, I plan to sequence genomes of these hybrids to better understand mechanisms of their evolution.
      - layout: top-middle
        title: Studying populations of emerging pathogen of oak trees in western USA
        link: 

  - title: Research talks # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 2023
        description: | # this will include new lines to allow paragraphs
            Kozhar O et al. Pathogen emergence in changing ecosystems: case study with Phellinus noxius in Eastern Asia, Australia, and the Pacifi c Islands. International Congress of Plant Pathology 2023. Lyon, France.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in science some of my other interests and hobbies are:
      - Rock climbing
      - Cycling
      - Hiking
      - Gardening
      - Mixing music
      - Art and craft projects


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
